---
  - name: Copy fallback default nginx config for demo purposes
    copy: src="{{role_dir}}/files/conf/demo.conf" dest="/etc/nginx/sites-enabled/demo.conf"

  - copy: src={{ item }} dest=/www/ owner=nginx group=root mode=755
    with_fileglob:
      - "/{{role_dir}}/files/www/*"

  - name: RUNIT | Creating /etc/service/nginx
    file: path="/etc/service/nginx" state="directory"

  - name: RUNIT | Template  /etc/service/nginx/run
    template: src="{{role_dir}}/templates/nginx/nginx.runit.j2" dest="/etc/service/nginx/run" mode="u=rwx,g=rx,o=rx"

  - block:

    - name: "SUPERVISORD | Template  {{supervisor_confd_path}}/nginx.conf"
      template: src="{{role_dir}}/templates/nginx/nginx.supervisord.j2" dest="{{supervisor_confd_path}}/nginx.conf" mode="u=rw,g=r,o=r"

    when: container_svc == "supervisord"

